require('plugins')
require('options')
require('mappings')
-- require('maps')
-- require('mappings')
require('custom_functions')



-- configs
require('config.telescope')
require('config.cmp')
-- require('config.harpoon')
require('config.lspsaga')
require('config.Comment')
require('config.hop')
require('config.numb')
-- require('config.trouble')
require('config.fzf-lua')
require('config.lir')
-- require('config.nvim_transparent')
-- require('config.nvim-tree')
-- require('config.github-theme')
require('config.lsp-config')
require('config.goto_preview')
require('config.lspkind')
